# Facephi SDK Dependencies
[versions]
kotlin = "2.2.20"
androidGradlePlugin = "8.13.0"
composePlugin = "1.9.0"
activityComposeVersion = "1.11.0"
coreKtxVersion = "1.17.0"
lifecycleRuntimeKtxVersion = "2.9.4"
napierVersion = "2.7.1"
lifecycle_viewmodel_version = '2.9.4'
kotlinxDatetime = "0.7.1"

# FACEPHI SDK VERSION
facephiVersion = "2.4.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle_viewmodel_version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
# Logs
napier = { module = "io.github.aakira:napier", version.ref = "napierVersion" }

# FACEPHI SDK
facephi-sdk = { module = "com.facephi.androidsdk:sdk", version.ref = "facephiVersion" }
facephi-selphi = { module = "com.facephi.androidsdk:selphi_component", version.ref = "facephiVersion" }
facephi-selphid = { module = "com.facephi.androidsdk:selphid_component", version.ref = "facephiVersion" }
facephi-recording = { module = "com.facephi.androidsdk:video_recording_component", version.ref = "facephiVersion" }
facephi-tracking = { module = "com.facephi.androidsdk:tracking_component", version.ref = "facephiVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
